#ifndef HAL_EXTENSION_ADC_HPP
#define HAL_EXTENSION_ADC_HPP

#ifndef CONFIG_DISABLE_MODULE_ADC

#include "HAL_Extension_adc_dma.hpp"

#endif // CONFIG_DISABLE_MODULE_ADC

#endif // HAL_EXTENSION_ADC_HPP